app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('dashboard');
});


// Rutas para aplicación
Route::resource('/paises', 'CountryController');
Route::resource('/departamentos', 'DepartamentController');
Route::resource('/ciudades', 'CityController');
Route::resource('/clientes', 'CustomerController');
Route::resource('/visitas', 'VisitController');


//Route::get('error', function () {
//    abort(404);
//});






// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

app/Visit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Visit extends Model
{
    use SoftDeletes;

    protected $table = 'visits';

    protected $fillable = ['seller_id', 'fecha', 'valor_neto', 'valor_visita', 'observaciones', 'customers_id'];

    protected $dates = ['deleted_at'];

    public function seller(){
        return $this->belongsTo(Seller::class);
    }

    public function customers(){
        return $this->belongsTo(Customer::class);
    }

    /*
     * Permite actualizar el valor de visita cuando se crea
     * o se actualiza el valor neto
     * */
    public function setValorNetoAttribute($value){
        //se toma el id del cliente actual
        $idcliente = intval($this->attributes['customers_id']);

        //busca el porcentaje de visitas del cliente agregado
        $porcentajevisita = Customer::find($idcliente);


        //se calcula el valor de la visita según la formula del cliente
        $valvisita = $value + $porcentajevisita->porcentaje_visitas;

        //se guarda el cálculo
        $this->attributes['valor_visita'] = $valvisita;
        //se pasa el valor sin modificaciones
        $this->attributes['valor_neto'] = $value;
    }


    /*
     * Permite actualizar el valor de visita cuando se crea
     * o se actualiza el customers_id (el cliente)
     * */
//    public function setCustomersIdAttribute($value){
//        //se toma el valor neto
//        dd($this);
//        $valorneto = intval($this->attributes['valor_neto']);
//
//        //busca el porcentaje de visitas del cliente agregado
//        $porcentajevisita = Customer::find($value);
//
//        //se calcula el valor de la visita según la formula del cliente
//        $valvisita = $valorneto + $porcentajevisita->porcentaje_visitas;
//
//        //se guarda el cálculo
//        $this->attributes['valor_visita'] = $valvisita;
//        //se pasa el valor sin modificaciones
//        $this->attributes['customers_id'] = $value;
//    }

}

app/Http/Controllers/VisitController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\VisitRequest;
use App\Visit;
use Illuminate\Auth\Guard;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;

class VisitController extends Controller
{
    public function __construct(Guard $auth)
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try{
            $visits = Visit::All();

            return view('visit.index', compact('visits'),['page_title'=>'Visitas']);
        } catch (\Exception $e) {
            return redirect::to('/dashboard')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try{
            $sellers = \App\Seller::lists('name', 'id');
            $customers = \App\Customer::lists('name', 'id');

            return view('visit.create', compact('sellers','customers'), ['page_title'=>'Nueva visita']);
        } catch (\Exception $e) {
            return redirect::to('/visitas')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(VisitRequest $request)
    {
        try{
            Visit::create([
                'customers_id'  => $request['customers_id'],
                'seller_id'     => $request['seller_id'],
                'valor_neto'    => $request['valor_neto'],
                'fecha'         => $request['fecha'],
                'observaciones' => $request['observaciones'],

            ]);

            return redirect('/visitas')->with('message', 'Nuevo Registro Creado');
        } catch (\Exception $e) {
            return redirect::to('/visitas')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try{
            $sellers = \App\Seller::lists('name', 'id');
            $customers = \App\Customer::lists('name', 'id');
            $visits = Visit::find($id);

            return view('visit.edit',compact('visits'),['sellers'=>$sellers,'customers'=>$customers,'page_title'=>'Editar Visita']);
        } catch (\Exception $e) {
            return redirect::to('/visitas')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(VisitRequest $request, $id)
    {
        try{
            $visit = Visit::find($id);

            $visit->fill($request->all());
            $visit->save();

            Session::flash('message','Visita Actualizada');
            return redirect::to('/visitas');
        } catch (\Exception $e) {
            return redirect::to('/visitas')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            //Visit::destroy($id);
            $visit = Visit::find($id);
            $visit->delete();
            Session::flash('message','Registro Eliminado');
            return redirect::to('/visitas');
        } catch (\Exception $e) {
            return redirect::to('/visitas')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }
    }
}

resources/views/visit/create.blade.php
@extends('layouts.boots')

@section('content')

    {!!Form::open(['route'=>'visitas.store','method'=>'POST'])!!}

        @include('visit.forms.campos')

    {!!Form::close()!!}

@stop

resources/views/visit/edit.blade.php
@extends('layouts.boots')

@section('content')

    {!!Form::model($visits,['route'=> ['visitas.update', $visits->id], 'method'=>'PUT'])!!}

        @include('visit.forms.campos')

    {!!Form::close()!!}

    {!!Form::open(['route'=>['visitas.destroy', $visits->id],'method'=>'DELETE'])!!}
        {!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
    {!!Form::close()!!}

@stop

resources/views/visit/index.blade.php
@extends('layouts.boots')

@section('content')
    @if(Session::has('message'))
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{Session::get('message')}}
        </div>
    @endif

    <div class='form-group'>
        <a href="{{ url('/visitas/create')}}" class="btn btn-primary">Agregar Visita</a>
    </div>
    <br>

    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Cliente</th>
                <th>Vendedor</th>
                <th>Fecha de Venta</th>
                <th>Valor Neto</th>
                <th>Valor Visita</th>
                <th>Observaciones</th>
                <th></th>
            </tr>
            </thead>
            @foreach($visits as $visit)
                <tbody>
                <tr>
                    <td>{{$visit->customers->name}}</td>
                    <td>{{$visit->seller->name}}</td>
                    <td>{{$visit->fecha}}</td>
                    <td>{{$visit->valor_neto}}</td>
                    <td>{{$visit->valor_visita}}</td>
                    <td>{{$visit->observaciones}}</td>
                    <td>{!!link_to_route('visitas.edit', $title = 'Editar', $parameters = $visit->id, $atributes = ['class'=>'btn btn-primary'])!!}</td>
                    <td>
                        {!!Form::open(['route'=>['visitas.destroy', $visit->id],'method'=>'DELETE'])!!}
                            <div class='form-group'>
                                {!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
                            </div>
                        {!!Form::close()!!}
                    </td>
                </tr>
                </tbody>
            @endforeach
        </table>
    </div>

@stop