app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('dashboard');
});


// Rutas para aplicación
Route::resource('/paises', 'CountryController');
Route::resource('/departamentos', 'DepartamentController');
Route::resource('/ciudades', 'CityController');
Route::resource('/clientes', 'CustomerController');
Route::resource('/visitas', 'VisitController');


//Route::get('error', function () {
//    abort(404);
//});






// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

app/Departament.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Departament extends Model
{
    protected $table = 'departaments';

    protected $fillable = ['name', 'country_id'];

    protected $dates = ['deleted_at'];

    //un departamento pertenece a un país
    public function county(){
        return $this->belongsTo(Country::class);
    }

    //un departamento tiene N ciudades
    public function cities(){
        return $this->hasMany(City::class);
    }
}

app/Http/Controllers/DepartamentController.php
<?php

namespace App\Http\Controllers;

use App\Departament;
use Illuminate\Auth\Guard;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;

class DepartamentController extends Controller
{
    public function __construct(Guard $auth)
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try{
            $departaments = Departament::All();

            return view('departament.index', compact('departaments'),['page_title'=>'Departamentos']);
        } catch (\Exception $e) {
            return redirect::to('/dashboard')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try{
            $countries = \App\Country::lists('name', 'id');

            return view('departament.create', compact('countries'), ['page_title'=>'Crear Departamento']);
        } catch (\Exception $e) {
            return redirect::to('/departamentos')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        try{
            Departament::create([
                'name'  => $request['name'],
                'country_id' => $request['country_id'],
            ]);
    
            return redirect('/departamentos')->with('message', 'Nuevo Registro Creado');
        } catch (\Exception $e) {
            return redirect::to('/departamentos')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try{
            $countries = \App\Country::lists('name', 'id');
            $departaments = Departament::find($id);
    
            return view('departament.edit',compact('countries'),['departaments'=>$departaments,'page_title'=>'Editar Departamento']);
        } catch (\Exception $e) {
            return redirect::to('/departamentos')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try{
            $departament = Departament::find($id);
    
            $departament->fill($request->all());
            $departament->save();
    
            Session::flash('message','Departamento Actualizado');
            return redirect::to('/departamentos');
        } catch (\Exception $e) {
            return redirect::to('/departamentos')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/departament/create.blade.php
@extends('layouts.boots')

@section('content')

    {!!Form::open(['route'=>'departamentos.store','method'=>'POST'])!!}

    @include('departament.forms.campos')

    {!!Form::close()!!}

@stop

resources/views/departament/edit.blade.php
@extends('layouts.boots')

@section('content')


    {!!Form::model($departaments,['route'=> ['departamentos.update', $departaments->id], 'method'=>'PUT'])!!}

        @include('departament.forms.campos')

    {!!Form::close()!!}

@stop

resources/views/departament/index.blade.php
@extends('layouts.boots')

@section('content')
    @if(Session::has('message'))
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{Session::get('message')}}
        </div>
    @endif

    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Nombre</th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            @foreach($departaments as $departament)
                <tbody>
                <tr>
                    <td>{{$departament->name}}</td>
                    <td>{!!link_to_route('departamentos.edit', $title = 'Editar', $parameters = $departament->id, $atributes = ['class'=>'btn btn-primary'])!!}</td>
                </tr>
                </tbody>
            @endforeach
        </table>
    </div>

@stop