app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', function () {
    return view('dashboard');
});


// Rutas para aplicación
Route::resource('/paises', 'CountryController');
Route::resource('/departamentos', 'DepartamentController');
Route::resource('/ciudades', 'CityController');
Route::resource('/clientes', 'CustomerController');
Route::resource('/visitas', 'VisitController');


//Route::get('error', function () {
//    abort(404);
//});






// Authentication routes...
Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

// Registration routes...
Route::get('auth/register', 'Auth\AuthController@getRegister');
Route::post('auth/register', 'Auth\AuthController@postRegister');

// Password reset link request routes...
Route::get('password/email', 'Auth\PasswordController@getEmail');
Route::post('password/email', 'Auth\PasswordController@postEmail');

// Password reset routes...
Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
Route::post('password/reset', 'Auth\PasswordController@postReset');

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Crypt;

class Customer extends Model
{
    use SoftDeletes;

    protected $table = 'customers';

    protected $fillable = ['name', 'nit', 'direccion', 'telefono', 'city_id', 'cupo', 'saldo_cupo', 'porcentaje_visitas'];

    //desencripta el NIT
    public function getNitAttribute($value)
    {
        return Crypt::decrypt($value);
    }

    //Encripta el NIT
    public function setNitAttribute($value)
    {
        $this->attributes['nit'] = Crypt::encrypt($value);
    }
    
    public function visit(){
        return $this->hasMany(Visit::class);
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use App\Http\Requests\CustomerRequest;
use Illuminate\Auth\Guard;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;

class CustomerController extends Controller
{
    public function __construct(Guard $auth)
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try{
            $customers = Customer::All();

            return view('customer.index', compact('customers'),['page_title'=>'Clientes']);
        } catch (\Exception $e) {
            return redirect::to('/dashboard')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try{
            $cities = \App\City::lists('name', 'id');

            return view('customer.create', compact('cities'), ['page_title'=>'Crear Cliente']);
        } catch (\Exception $e) {
            return redirect::to('/clientes')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CustomerRequest $request)
    {
        try{
            Customer::create([
                'name'      => $request['name'],
                'nit'       => $request['nit'],
                'direccion' => $request['direccion'],
                'telefono'  => $request['telefono'],
                'city_id'   => $request['city_id'],
                'cupo'      => $request['cupo'],
                'saldo_cupo'=> $request['saldo_cupo'],
                'porcentaje_visitas'=> $request['porcentaje_visitas'],
            ]);

            return redirect('/clientes')->with('message', 'Nuevo Registro Creado');
        } catch (\Exception $e) {
            return redirect::to('/clientes')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try{
            $cities = \App\City::lists('name', 'id');
            $customers = Customer::find($id);
    
            return view('customer.edit',compact('customers'),['cities'=>$cities,'page_title'=>'Editar Cliente']);
        } catch (\Exception $e) {
            return redirect::to('/clientes')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }    
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CustomerRequest $request, $id)
    {
        try{
            $customer = Customer::find($id);
    
            $customer->fill($request->all());
            $customer->save();
    
            Session::flash('message','Registro Actualizado');
            return redirect::to('/clientes');
        } catch (\Exception $e) {
            return redirect::to('/clientes')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        }    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try{
            $customer = Customer::find($id);
            $customer->delete();
            Session::flash('message','Registro Eliminado');
            return redirect::to('/clientes');
        } catch (\Exception $e) {
            return redirect::to('/clientes')->with('message-error', 'Lo sentimos, algo salió mal. Vuelve a intentarlo, o comunícate con el administrador del sistema.');
        } 
    }
}

resources/views/customer/create.blade.php
@extends('layouts.boots')

@section('content')

    {!!Form::open(['route'=>'clientes.store','method'=>'POST'])!!}

        @include('customer.forms.campos')

    {!!Form::close()!!}

@stop

resources/views/customer/edit.blade.php
@extends('layouts.boots')

@section('content')


    {!!Form::model($customers,['route'=> ['clientes.update', $customers->id], 'method'=>'PUT'])!!}

        @include('customer.forms.campos')

    {!!Form::close()!!}

@stop

resources/views/customer/index.blade.php
@extends('layouts.boots')

@section('content')
    @if(Session::has('message'))
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            {{Session::get('message')}}
        </div>
    @endif

    <div class='form-group'>
        <a href="{{ url('/clientes/create')}}" class="btn btn-primary">Agregar Cliente</a>
    </div>
    <br>

    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Nombre</th>
                <th>NIT</th>
                <th>Dirección</th>
                <th>Teléfono</th>
                <th>Ciudad</th>
                <th>Cupo</th>
                <th>Saldo Cupo</th>
                <th>Porcentaje Visitas</th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            @foreach($customers as $customer)
                <tbody>
                <tr>
                    <td>{{$customer->name}}</td>
                    <td>{{$customer->nit}}</td>
                    <td>{{$customer->direccion}}</td>
                    <td>{{$customer->telefono}}</td>
                    <td>{{$customer->city_id}}</td>
                    <td>{{$customer->cupo}}</td>
                    <td>{{$customer->saldo_cupo}}</td>
                    <td>{{$customer->porcentaje_visitas}}%</td>
                    <td>{!!link_to_route('clientes.edit', $title = 'Editar', $parameters = $customer->id, $atributes = ['class'=>'btn btn-primary'])!!}</td>
                    <td>
                        {!!Form::open(['route'=>['clientes.destroy', $customer->id],'method'=>'DELETE'])!!}
                            <div class='form-group'>
                                {!!Form::submit('Eliminar',['class'=>'btn btn-danger'])!!}
                            </div>
                        {!!Form::close()!!}
                    </td>
                </tr>
                </tbody>
            @endforeach
        </table>
    </div>

@stop